recipes:
  enchanted_potato:
    result: "POTATO"
    amount: 1
    shape:
      - "DDD"
      - "DID"
      - "DDD"
    ingredients:
      D: "DIAMOND_BLOCK"
      I: "IRON_BLOCK"
    effects:
      - type: "REGENERATION"
        duration: 200
        amplifier: 1
      - type: "SPEED"
        duration: 300
        amplifier: 1
  enchanted_golden_apple:
    result: "GOLDEN_APPLE"
    amount: 1
    shape:
      - "GGG"
      - "GAG"
      - "GGG"
    ingredients:
      G: "GOLD_BLOCK"
      A: "APPLE"
    effects:
      - type: "REGENERATION"
        duration: 400
        amplifier: 2
